# Generated by Django 4.2.1 on 2023-05-27 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
